name: Lamp Deployment for Testing@1

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

jobs:
  #lint:
  #  name: Lint Ansible Playbook
  #  runs-on: ubuntu-latest

   # steps:
   # - name: Checkout sources
   #   uses: actions/checkout@v3
   # - name: Linting
    #  uses: ansible/ansible-lint-action@main
     # with:
      #  targets: |
       #   ansible/playbook.yml
       #   ansible/inventory.yml

        #args: "-c ansible/.ansible-lint"

    #- name: Publish Playbook Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: playbooks
     #   path: ansible


  deploy_to_test:
    name: Deploy to test
    runs-on: ubuntu-latest
    #needs: lint
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    
    - name: Install dependencies Including Ansible
      run: |
          python -m pip install --upgrade pip \
          && pip install pywinrm requests-credssp passlib msrest msrestazure
          && ansible-galaxy collection install azure.azcollection community.general community.hashi_vault \
          && pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

    #- uses: actions/download-artifact@v2
    #  with:
    #    name: playbooks
    #    path: ansible
    
    - uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ansible
        vault_password: ${{ secrets.VAULT_PASSWORD }}
        options: |
          --inventory inventory-test.yml
          --extra-vars "test_ssh_password=${{ Secrets.TEST_SSH_PASSWORD }}"
